"""added post comments revised

Revision ID: 7d2deca7931f
Revises: bc84ea9340be
Create Date: 2018-04-22 11:51:02.024724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2deca7931f'
down_revision = 'bc84ea9340be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comment_post_id'), 'post_comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comment_timestamp'), 'post_comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_comment_timestamp'), table_name='post_comment')
    op.drop_index(op.f('ix_post_comment_post_id'), table_name='post_comment')
    op.drop_table('post_comment')
    # ### end Alembic commands ###
