"""added attachments

Revision ID: b933345ff0d4
Revises: 7d2deca7931f
Create Date: 2018-04-23 11:34:27.969419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b933345ff0d4'
down_revision = '7d2deca7931f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('attachment', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'attachment')
    # ### end Alembic commands ###
