"""4/21 added admin

Revision ID: bc84ea9340be
Revises: dd897952f2d6
Create Date: 2018-04-21 19:55:19.510842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc84ea9340be'
down_revision = 'dd897952f2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
